version: "3"
services:
  fronted:
    build: ./frontend
    container_name: 'heros_api_front'
    # command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - "backend"
    stdin_open: true
    tty: true
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./backend
    container_name: 'heros_api_back'
    restart: 'always'
    # command: sh -c 'npm install; npm start'
    ports:
      - '5000:4000'
    volumes:
      - ./backend:/backend
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    container_name: 'mongo_db_heros'
    restart: 'always'
    ports:
      - "27018:27017"
    # logging:
      # driver: none