version: "3"
services:
  frontend:
    build: ./frontend
    container_name: 'herosspa_front'
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/usr/src/app-front
    depends_on:
      - 'backend'
    # stdin_open: true
    # tty: true

    # environment:
    #  - NODE_ENV=development
    #  - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    container_name: 'herosspa_back'
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app-back
    depends_on:
      - 'mongo-db'

  mongo-db:
    image: mongo
    container_name: 'herosspa_db'
    ports:
     - 27018:27017


